name: Deploy Node Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy code to EC2 and Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            rm -rf youtube_backend
            git clone https://github.com/chandrashekhar3337/youtube_backend.git
            cd youtube_backend

            docker stop backend || true
            docker rm backend || true

            docker build -t youtube-backend .

            docker run -d \
              --name backend \
              -p 3000:3000 \
              -e PORT="${{ secrets.PORT }}" \
              -e MONGODB_URI="${{ secrets.MONGODB_URI }}" \
              -e ACCESS_TOKEN_SECRET="${{ secrets.ACCESS_TOKEN_SECRET }}" \
              -e ACCESS_TOKEN_EXPIRARY="${{ secrets.ACCESS_TOKEN_EXPIRARY }}" \
              -e REFRESH_TOKEN_SECRET="${{ secrets.REFRESH_TOKEN_SECRET }}" \
              -e REFRESH_TOKEN_EXPIRARY="${{ secrets.REFRESH_TOKEN_EXPIRARY }}" \
              youtube-backend
